services:
  - type: web
    name: team-task-manager-api
    runtime: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: mkdir -p /tmp && touch /tmp/db.sqlite3 && python manage.py migrate --noinput && gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
